title: SECON
description: Archive of conferences on the economics of information security

# Ogni file conferences/<slug>.yml diventa site.data.<slug>
data_dir: conferences

plugins:
  - jekyll-seo-tag

exclude:
  - pages-themes-cayman-56aa6db
  - _templates
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md