title: WEIS
description: Papers of conferences on the economics of information security

# conferences/yml/<slug>.yml    -> site.data.yml.<slug>      (complete program)
# conferences/papers/<slug>.yml -> site.data.papers.<slug>  (main page)
data_dir: conferences

plugins:
  - jekyll-seo-tag

exclude:
  - pages-themes-cayman-56aa6db
  - _templates
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md